#!/usr/bin/env bash
# script that installs nginx:

#install and update nginx
sudo apt-get -y install nginx

#update nginx
sudo apt-get -y update

#nginx start
sudo service nginx start

# allow https for nginx
sudo ufw allow "Nginx Http"

# create new file with new text
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# restart nginx
sudo service nginx restart
