#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

#get updates
sudo apt-get -y update

#install nginx
sudo apt-get -y install nginx

#nginx start
sudo service nginx start

# allow https for nginx
sudo ufw allow "Nginx Http"

echo "server {
      location / {
          # First attempt to serve request as file, then
          # as directory, then fall back to displaying a 404.
          try_files \$uri \$uri/ =404;
      }
      location /redirect_me {
          return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
      }
}" | sudo tee /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart;
