#!/usr/bin/env bash
# script that installs nginx:

#get updates
sudo apt-get -y update

#install nginx
sudo apt-get -y install nginx

#nginx start
service nginx start

# allow https for nginx
sudo ufw allow "Nginx Http"

redirect_url='https://www.youtube.com/watch?v=QH2-TGUlwu4'
comment='#Redirect to new url';
new_string="location /redirect_me {\n$comment\n\nreturn 301 $redirect_url;\n"
sudo sed -i "s/location / {/$new_string/" /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
