#!/usr/bin/env bash


sudo sed -i 's/add_header X-Served-By $host;//' /etc/nginx/sites-enabled/default
sudo sed -i 's/add_header X-Served-By $host;//' /etc/nginx/sites-available/default

sudo sed -i 's/server_name _;/server_name _;\n\n\tadd_header X-Served-By $host;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/server_name _;/server_name _;\n\n\tadd_header X-Served-By $host;/' /etc/nginx/sites-available/default
sudo service nginx restart
