#!/usr/bin/env bash
#script to add custom header 

#Install nginx
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install nginx

# start nginx
sudo service nginx start

sudo sed -i 's/add_header X-Served-By $hostname;//' /etc/nginx/sites-enabled/default
sudo sed -i 's/add_header X-Served-By $hostname;//' /etc/nginx/sites-available/default

sudo sed -i 's/server_name _;/server_name _;\n\n\tadd_header X-Served-By $hostname;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/server_name _;/server_name _;\n\n\tadd_header X-Served-By $hostname;/' /etc/nginx/sites-available/default

#restart nginx
sudo service nginx restart
