#!/usr/bin/env bash
# Script to setup and install HaProxy

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

# enable HAProxy to be started by the init script.
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

print "backend manucho-servers
\tbalance roundrobin
\tserver 103008-web-02 34.232.78.67:80 check
\tserver 103008-web-01 52.204.99.18:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
