#!/usr/bin/env bash
# Script to setup and install HaProxy

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# enable HAProxy to be started by the init script.
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo '
frontend manuchodev.tech
    bind *:80
    default_backend manuchos-backed

backend manuchos-backed
    balance roundrobin
    mode http
    server 103008-web-02 34.232.78.67 check
    server 103008-web-01 52.204.99.18 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
