#!/usr/bin/env bash
# Script to setup and install HaProxy

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend manuchodev.tech
    bind *:80
    mode http
    default_backend manuchos-backed

backend manuchos_backed
    balance roundrobin
    server 103008-web-02 34.232.78.67:80 check
    server 103008-web-01 52.204.99.18:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start
