#!/usr/bin/env bash
# script to run nginx on port 80

sudo service apache2 stop
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo service nginx start

cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx reload
