#!/usr/bin/env bash
# script to run nginx on port 80

# kill all running docker container
sudo docker kill "$(sudo docker ps -q)"

# run docker to listen to port 80
sudo docker run -p 80:80 -d -it holbertonschool/265-0

# docker image id
CONTAINER_ID="$(sudo docker ps -q)"

echo "sudo service apache2 stop" | sudo docker exec -i "$CONTAINER_ID" /bin/bash
echo "sudo apt-get -y update && sudo apt-get -y upgrade" | sudo docker exec -i "$CONTAINER_ID" /bin/bash
echo "sudo apt-get -y install nginx" | sudo docker exec -i "$CONTAINER_ID" /bin/bash
echo "sudo service nginx start" | sudo docker exec -i "$CONTAINER_ID" /bin/bash
