#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd

FILE="/etc/passwd"
IFS=":"
while read -r line
do
	USERNAME="$(echo "$line" | cut -d "$IFS" -f 1)"
	PASSWORD="$(echo "$line" | cut -d "$IFS" -f 2)"
	USER_ID="$(echo "$line" | cut -d "$IFS" -f 3)"
	GROUP_ID="$(echo "$line" | cut -d "$IFS" -f 4)"
	USER_ID_INFO="$(echo "$line" | cut -d "$IFS" -f 5)"
	HOME_DIRECTORY="$(echo "$line" | cut -d "$IFS" -f 6)"
	COMMAND_SHELL="$(echo "$line" | cut -d "$IFS" -f 7)"

	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"

done < "$FILE"
