#!/usr/bin/env bash
# script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

range=0
while [ $range -lt 10 ];
do
	if [ "$range" -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((range++))
done
