#!/usr/bin/env bash
# script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

range=1
while [ $range -lt 21 ];
do
	case "$range" in
		"4") echo "$range"; echo "bad luck from China";;
		"9") echo "$range"; echo "bad luck from Japan";;
		"17") echo "$range"; echo "bad luck from Italy";;
		*) echo "$range"
	esac

	((range++))
done
