#!/usr/bin/env bash
# script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

LIST="$(ls .)"
for i in $LIST;
do
	NEWNAME="$(echo "$i" | cut -d '-' -f 2)"
	echo "$NEWNAME"
done	
