#!/usr/bin/env bash
# script that impliments all firewall rules to our server
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
#   22 (SSH)
#   443 (HTTPS SSL)
#   80 (HTTP)

sudo ufw default deny incoming
sudo ufw allow OpenSSH
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
